http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  # ovdje definiramo api servis i njegove rute
  test:
    host: localhost
    paths: ["/test", "/test/*"]
  users:
    host: localhost
    paths: ["/users", "/users/*"]
  expenses:
    host: localhost
    paths: ["/expenses", "/expenses/*"]
  invoiceScanner:
    host: localhost
    paths: ["/scan", "/scan/*"]
  accounts:
    host: localhost
    paths: ["/accounts", "/accounts/*"]
  categories:
    host: localhost
    paths: ["/categories", "/categories/*"]
  personalization:
    host: localhost
    paths: ["/personalization", "/personalization/*"]
serviceEndpoints:
  # ovdje definiramo lokalni endpoint (za testing)
  testService:
    url: "http://localhost:1337"
  usersService:
    url: "http://localhost:1339"
  expensesService:
    url: "http://localhost:1340"
  invoiceScannerService:
    url: "http://localhost:1338"
  accountsService:
    url: "http://localhost:1341"
  personalizationService:
    url: "http://localhost:1342"
  categoriesService:
    url: "http://localhost:1343"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  # ovdje definiramo vezu izmedu api servisa i njegovog endpointa
  testPipeline:
    apiEndpoints:
      - test
      - invoiceScanner
    policies:
      - proxy:
          - action:
              serviceEndpoint: testService
              changeOrigin: true
  userPipeline2:
    apiEndpoints:
      - test
      - invoiceScanner
    policies:
      - proxy:
          - action:
              serviceEndpoint: invoiceScannerService
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true
  expensesPipeline:
    apiEndpoints:
      - expenses
    policies:
      - proxy:
          - action:
              serviceEndpoint: expensesService
              changeOrigin: true
  accountsPipeline:
    apiEndpoints:
      - accounts
    policies:
      - proxy:
          - action:
              serviceEndpoint: accountsService
              changeOrigin: true
  personalizationPipeline:
    apiEndpoints:
      - personalization
    policies:
      - proxy:
          - action:
              serviceEndpoint: personalizationService
              changeOrigin: true
  categoriesPipeline:
    apiEndpoints:
      - categories
    policies:
      - proxy:
          - action:
              serviceEndpoint: categoriesService
              changeOrigin: true
